/// <reference types="@cloudflare/vitest-pool-workers/types" />
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

// The vitest-pool-workers `env` is typed as `Cloudflare.Env` (generated by
// `wrangler types`). DB is already there from the binding; TEST_MIGRATIONS is a
// test-only binding declared in vitest.config.ts, so augment the namespace.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
